language: cpp

cache:
  ccache: true

env:
  global:
  # AWS S3 creds
  # access key
  - secure: "MfhOg+84yb4ZHB2tM8PIPFQX2Y+WLN0I0iiAgyLC4KaHPUoNOyloe9yk6OjV7Lj7SZWqTlQUsqHa8S9mOUswGIody1Ydglo4RvyGOKCd8I6b2ri/jE8qHVuD9sO+sNlIxq4YqqG/qReTsbSs2YEgLneZUCYLCk/fihl8L6eVuSc="
  # secret
  - secure: "JRQVU2zgC3hY6CEY+Crmh/upp93En0BzKaLcsuBT538johNlK7m5hn3m2UOw63seLvBvVaKKWUDj9N986a3DwcXxWPMyF/9ctXgNWy39WzaVWxrbVR5nQB1fdiRp5YEgkoVN+gEm3OVF7sV5AGzh5/8CvEdRCoTLIGgMGHxW9mc="

  # ccache
  - USE_CCACHE=1
  - CCACHE_COMPRESS=1
  - CCACHE_MAXSIZE=200M
  - CCACHE_CPP2=1

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
       - CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
       - CEF_BUILD_VERSION=3770
      before_install: "./CI/install-dependencies-osx.sh"
      before_script: "./CI/before-script-osx.sh"
      before_deploy: "./CI/before-deploy-osx.sh"

    - os: linux
      dist: xenial
      sudo: required
      before_install: "./CI/install-dependencies-linux.sh"
      before_script: "./CI/before-script-linux.sh"

script: cd ./build && make -j4 && cd -

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  local_dir: nightly
  bucket: obs-nightly
  region: us-west-2
  acl: public_read
  on:
    repo: obsproject/obs-studio
    condition: "$TRAVIS_OS_NAME = osx"
    all_branches: true

notifications:
  webhooks:
    urls:
      - secure: EVI2cu5OnNxVTl4jdVppps7O869gGN1PDcSi8fqq/HJVM5kif8iDe4wCrIKv6yWrK3dSNwRgBAwpcPZglRJnKRh23PdFoCdnTjgzBQlmjUR6BYlunQvoKR9mVX6AdT8zrFDgmtC4aOtGD2paptpqt+Equo25KrLwv+qOHJOTrSQ=
    on_success: always
    on_failure: always

