image:
 - Ubuntu
 - Visual Studio 2017

environment:
  CURL_VERSION: 7.56.1
  CEF_VERSION: 75.1.16+g16a67c4+chromium-75.0.3770.100
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  TWITCH-CLIENTID:
    secure: D3vFGk41HZaJWAZu5slwAHZhB868mGI2aIMS03L2rt4=
  TWITCH-HASH:
    secure: IRP5JLwBmPMjA7ADbZu6x2u4thqeEF9HaU1xolhaj74=
  MIXER-CLIENTID:
    secure: lQXRRvkeZDVSTUcSaR/kthiKu89K18IubKN913PC0ldjHBQ6sWa8a/t4i1f441N3RPfzAbTrXf2ijRCYYub2Qw==
  MIXER-HASH:
    secure: fIxeDxHkiNodwPeNGX+E9tSpyjg/XuT+U9N+jtpT7xU=
  RESTREAM-CLIENTID:
    secure: 4KGqX7PbL100GhXWzMFziaHrD/XT9/QKFTGinmPqwOkfRSMMEkUyL998/z3cclUd
  RESTREAM-HASH:
    secure: +tu/wCCG3tXnFpjzzXF6zyAOJyt8w48qx47K1bIn/Gs=

install:
  - git submodule update --init --recursive
  - cmd: C:\projects\obs-studio\CI\install-qt-win.cmd
  - cmd: C:\projects\obs-studio\CI\install-script-win.cmd
  - sh: ./CI/install-dependencies-linux-ubuntu16.sh
  - sh: ./CI/before-script-linux.sh
  - sh: ./CI/install-script-linux.sh

build_script:
  - cmd: call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - sh: cd ./build && make -j4 && cd -

before_deploy:
  - cmd: C:\projects\obs-studio\CI\before-deploy-win.cmd

deploy_script:
  - ps: Push-AppveyorArtifact "build.zip" -FileName "$(git describe).zip"

test: off

cache:
  - dependencies2017.zip
  - vlc.zip
  - 'cef_binary_%CEF_VERSION%_windows32_minimal.zip'
  - 'cef_binary_%CEF_VERSION%_windows64_minimal.zip'
  - Qt_5.10.1.7z

notifications:
  - provider: Webhook
    url:
      secure: k1kpaz4CB5Rg5a3MTb4XKnd76fJ+9ozz5RACVnNjdgmAjA1OSssZ6LZ3g0NGfzc/
    headers:
      Authorization:
        secure: A0PBwpHtsYzBOuye1EeS0fl562T0NZEInwZp0ZVER1wLQSeE6gzWGrRo2a0E7hii
