name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        choco install -y visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Component.VC.ATL --add Microsoft.VisualStudio.Component.Windows10SDK.20348 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        choco install -y cmake git

    - name: Create build directory
      run: |
        mkdir build_x64

    - name: Configure build
      run: |
        cd build_x64
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build obs-studio
      run: |
        cd build_x64
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build_x64
        .\rundir\Release\bin\64bit\obs64.exe --tests

    - name: Package distribution
      run: |
        cd build_x64
        cmake --build . --config Release --target package
